name = "sisyphus"
main = "src/index.ts"
compatibility_date = "2023-10-30"
account_id = "9ddae624c98677d68d93df6e524a6061"

[vars]
LABRINTH_URL = "http://127.0.0.1:8000/v2/"
LABRINTH_ADMIN_SECRET = "feedbeef"
RATE_LIMIT_IGNORE_KEY = "feedbeef"

[env.staging.vars]
LABRINTH_URL = "https://staging-api.modrinth.com/v2/"
LABRINTH_ADMIN_SECRET = "feedbeef"
RATE_LIMIT_IGNORE_KEY = "feedbeef"

[env.prod.vars]
LABRINTH_URL = "https://api.modrinth.com/v2/"
LABRINTH_ADMIN_SECRET = "feedbeef"
RATE_LIMIT_IGNORE_KEY = "feedbeef"

[[r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn-staging"
preview_bucket_name = "modrinth-cdn-staging"

[[env.staging.r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn-staging"

[[env.prod.r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn"
