name = "sisyphus"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[vars]
LABRINTH_URL = "http://127.0.0.1:8000/v2/"

[env.staging.vars]
LABRINTH_URL = "https://staging-api.modrinth.com/v2/"

[env.production.vars]
LABRINTH_URL = "https://api.modrinth.com/v2/"

[[r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn-staging"
preview_bucket_name = "modrinth-cdn-staging"

[[env.staging.r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn-staging"

[[env.production.r2_buckets]]
binding = "MODRINTH_CDN"
bucket_name = "modrinth-cdn"
